version: '3.7'
services:
  mysql:
    image: mysql:5.6
    command: --sql_mode="" --default-time-zone="+00:00"  --innodb-buffer-pool-size=8G --innodb-log-buffer-size=256M --innodb-log-file-size=1G --innodb-write-io-threads=16 --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_db
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ‘8080:8080’
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ‘./Portfolio/portfolio_back/public/:/usr/src/app’
      - ‘./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro’
    ports:
      - ’80:80′
    depends_on:
      - php